name: CI

on:
  push: 
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubantu-latest
    step:
      - name: check out code
        use: actions/checkout@v4
      - name: Setup Node js Envirorment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Pnpm
        run: npm install -g pnpm
      - name: Install Dependency
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test  